---
resource_types:
- name: ftp-resource
  type: docker-image
  source:
      repository: machinerytool/concourse-lftp-resource
      tag: latest

resources:
- name: fogger-code
  type: git
  source:
    uri: https://github.com/elrot/fgr.git
    branch: master

- name: fogger-ci
  type: git
  source:
    uri: https://github.com/elrot/fgr-ci.git
    branch: master

- name: midnight-timer
  type: time
  source:
    interval: 2m

jobs:
- name: nightly-build
  public: true
  serial: true
  plan:
  - get: fogger-ci
  - get: fogger-code
  - get: midnight-timer
    trigger: true
  - task: fogger-edge-nightly-build
    file: fogger-ci/tasks/build.yml
  
  - task: show-binaries
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: busybox}

      inputs:
      - name: fogger-ci
      - name: fogger-binaries

      run:
        path: fogger-ci/scripts/show_files.sh
                                            
                                      