---
platform: linux

image_resource:
  type: docker-image
  source: {repository: elrot/fgr-builder, tag: latest}

inputs:
- name: fogger-ci
- name: fogger-code
  path: gopath/src/github.com/elrot/fgr

outputs:
- name: fogger-binaries

run:
  path: fogger-ci/scripts/build.sh
