---
platform: linux

image_resource:
  type: docker-image
  source: {repository: elrot/mister-builder, tag: latest}

inputs:
- name: mister-ci
- name: mister-code
  path: gopath/src/github.com/elrot/mister

outputs:
- name: mister-binaries

run:
  path: mister-ci/scripts/build.sh
