---
resource_types:
- name: ftp
  type: docker-image
  source:
      repository: elrot/concourse-lftp-resource
      tag: latest

- name: slack
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: mister-code
  type: git
  source:
    uri: https://github.com/elrot/mister.git
    branch: master

- name: mister-ci
  type: git
  source:
    uri: https://github.com/elrot/mister-ci.git
    branch: master

- name: mister-ftp
  type: ftp
  source:
    url: ((mister-ftp-url))

- name: mister-slack
  type: slack
  source:
    url: ((mister-slack-webhook))

- name: after-midnight
  type: time
  source:
    start: 12:00 AM
    stop: 1:00 AM
    location: Europe/Warsaw

jobs:
- name: nightly-build
  public: true
  serial: true
  build_logs_to_retain: 10
  plan:
  - get: mister-ci
  - get: mister-code
  - get: after-midnight
    trigger: true

  - task: build
    file: mister-ci/tasks/build.yml
  
  - put: mister-ftp
    params:
      path: mister-binaries/

  - put: mister-slack
    params:
      channel: '#ci'
      username: Concourse
      text: |
        Nightly build finished
                                            
                                      
