---
resource_types:
- name: ftp-resource
  type: docker-image
  source:
      repository: machinerytool/concourse-lftp-resource
      tag: latest

resources:
- name: mister-code
  type: git
  source:
    uri: https://github.com/elrot/mister.git
    branch: master

- name: mister-ci
  type: git
  source:
    uri: https://github.com/elrot/mister-ci.git
    branch: master

- name: midnight-timer
  type: time
  source:
    interval: 2m

jobs:
- name: nightly-build
  public: true
  serial: true
  plan:
  - get: mister-ci
  - get: mister-code
  - get: midnight-timer
    trigger: true

  - task: build
    file: mister-ci/tasks/build.yml
  
                                            
                                      